### ISSUE TITLE
gulp task doesn't exit

### ISSUE THREAD

**Issue by zbyte64** [jaysoo/gulp-dss#2]
Gulp version: 3.8.10

My task:

```
gulp.task('styleguide', function(callback) {
  return gulp.src('clients/boss/less/*.less')
    .pipe(dss({
      output: 'styleguide.html',
      //templatePath: path.join(__dirname, 'templates')
    }))
    .pipe(gulp.dest('dist/boss'));
});
```

The task completes but I have to Ctrl+C to get my prompt back (Ubuntu 14.04)

**Comment by jaysoo** [comment]
I'll take a look when I get the chance.

**Comment by viktorbergehall** [comment]
Add watch: false to nunjucks configure
nunjucks.configure(opts.templatePath || path.join(__dirname, 'templates'), {watch: false});

**Comment by jaysoo** [comment]
@viktorbergehall Thanks Viktor
